### ISSUE TITLE
Create a better icon for Hydrator

### ISSUE THREAD

**Issue by devcer** [devcer/hydrator#14]
We have been using this icon for more than 2 years now. Suggest a better icon for this add-on

**Comment by 20Koen02** [comment]
I will give it a go. Stay tuned.

**Comment by devcer** [comment]
Cool! all the best @20Koen02

**Comment by 20Koen02** [comment]
Here it is. I included the Illustrator file.
If you like it but something needs changing (like the colors) I can do that for you.
I hope you like it @devcer

**Comment by devcer** [comment]
@20Koen02 The design looks great. Two suggestions/requests.
* We updated the theme colors of the addon to this -> https://user-images.githubusercontent.com/50954098/94829120-c5eb1980-043c-11eb-8245-14cc22f2d2db.png 
Maybe you should use colors related to this?
Select tailwind from the dropdown and you will find the color codes here -> https://theme-ui.com/demo
* The glass looks like a glass of milk. Do you think we could do anything to resemble water? (need your opinion on this)

**Comment by 20Koen02** [comment]
Alright. I will post the revisions here, and then make a PR of the final revision

**Comment by 20Koen02** [comment]
revision 1: 
![afbeelding](https://user-images.githubusercontent.com/33985194/95015173-d0c7c900-064b-11eb-94c2-bc5e13a6a068.png)

**Comment by 20Koen02** [comment]
Do you want it to be a circle, rounded rectangle or square?

**Comment by devcer** [comment]
@20Koen02 This looks perfect. Please push your changes to the PR. I will test and merge it.

**Comment by deepharshsri** [comment]
Hi there, I have an awesome icon for that.

**Comment by deepharshsri** [comment]
Can I make a PR?

**Comment by 20Koen02** [comment]
@devcer see #20 for the PR

**Comment by devcer** [comment]
Fixed in https://github.com/devcer/hydrator/pull/20!
