### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by devcer** [devcer/hydrator#2]
* [x] Create `CONTRIBUTING.md` file in the root folder 
* [x] Add `How to Contribute` instructions to the file

Please use markdown!

**Comment by MitanshiKshatriya** [comment]
Hi, would like to add contribution section to README.md . Could I be assigned to it?

**Comment by shikhar8434** [comment]
Hello I would like to contribute to the README.md , I would be very glad to help!

**Comment by devcer** [comment]
@MitanshiKshatriya Assigning this to you. You can submit your PR by Oct 2nd End of the Day IST. Else, I will pass this to the next contributor on the list. Happy Hacktoberfest.

**Comment by MitanshiKshatriya** [comment]
thanks! would definitely submit within time.

**Comment by sakshi006** [comment]
@devcer  Hello I would like to contribute to the README.md. Could i be assigned?

**Comment by xxKeefer** [comment]
looks like you got a few on this, but i would be happy to help as well

**Comment by yahayakenny** [comment]
Hello, please I would also like to contribute to the README.md, any openings?

**Comment by Priyanshu2802** [comment]
Can I also contribute in README.md

**Comment by noviyana12** [comment]
can I contribute in README.md?

**Comment by devcer** [comment]
This issue is still open! Any of you can pick an issue and submit a PR. The changes should be something similar like -> https://github.com/devcer/hydrator/pull/10

**Comment by mohitsaha** [comment]
I have added PR of contributing.md, please check that.

**Comment by devcer** [comment]
An example of a good `CONTRIBUTION.md` could be -> https://github.com/devcer/CapShun/blob/master/CONTRIBUTING.md

This issue is still open.

**Comment by vismitap** [comment]
Hello! I have raised a PR #22. Please review and suggest changes if any.
