### ISSUE TITLE
Improve UI of the add-on popup

### ISSUE THREAD

**Issue by devcer** [devcer/hydrator#3]
* [ ] Clone and run this add-on
* [ ] Find the `popup` related code in the popup folder
* [ ] Use your skill and judgment to improve the UI of the popup

**Comment by jcads** [comment]
Hi, I would like to work on the UI pop-up. Can I be assigned to this?

**Comment by SaiKiranRebba** [comment]
hi @devcer . May i know that are you using any frameworks or pure HTML. Im a Vuejs developer. I would like to work on this. Thank you

**Comment by devcer** [comment]
@jcads Done. All the best.
