### ISSUE TITLE
Suggest few more health tips from drinking water

### ISSUE THREAD

**Issue by devcer** [devcer/hydrator#5]
You can find the existing health facts from drinking water [here](https://github.com/devcer/hydrator/blob/master/background.js)

* [ ] Suggest new facts about benefits from drinking water

**Comment by paulopacitti** [comment]
I'd like to work in this! Could I be assigned to it? ✨

**Comment by devcer** [comment]
@paulopacitti Done. Let me know if you have any questions.

**Comment by Saksham-Katiyar** [comment]
I would like to contribute here. May I add further more facts ??
